#spring:
#  application:
#    name: spring-cloud-data-v1
#  profiles:
#    active:  dev
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#    username: root
#    password: accp
#    initialSize: 5
#    maxActive: 10
#    maxWait: 3000
##    druid:
##      filters: stat
##      maxActive: 20
##      initialSize: 1
##      maxWait: 60000
##      minIdle: 1
##      timeBetweenEvictionRunsMillis: 60000
##      minEvictableIdleTimeMillis: 300000
##      validationQuery: select 'x'
##      testWhileIdle: true
##      testOnBorrow: false
##      testOnReturn: false
##      poolPreparedStatements: true
##      maxOpenPreparedStatements: 20
#
#
#
#
#
#server:
#  port: 8001
#  http2:
#    enabled: true
#  undertow:
#      io-threads: 16
#      worker-threads: 256
#      buffer-size: 1024
#      buffers-per-region: 1024
#      direct-buffers: true
#  compression:
#    enabled: true
#
#
#center:
#  name: turing_center
#  token-header: center-auth
#  expire: 3600
#  rsa-secret: xx112^%3^(WE45WET
#  site:
#    token-header: site-auth
#    expire: 3600
#    rsa-secret: xx112^%3^(WE45WET
#jwt:
#  token-header: Authorization
#  expire: 3600
#  rsa-secret: xx112^%3^(WE45WET
#
#
#eureka:
#  instance:
#    healthCheckUrlPath: /health
#    # docker 部署开启
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    status-page-url: http://localhost:${server.port}/swagger-ui.html
#  client:
#    serviceUrl:
#      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:7001}/eureka/
#
#
## 配置swagger
#swagger:
#  enabled: true
#  base-package: com.tx
#  title: spring-cloud-data-v1
#  version: 1.0.0.SNAPSHOT
#  description: 数据服务
#  contact:
#    name: admin
#
#logging:
#  config: springcloud-data/src/main/resources/logback.xml
#  level:
#    com.tx: trace   #在生产环境上，将这个日志级别再设置成 error 级别
#    tk:
#      mybatis: debug
#
#
#mybatis:
#  mapper-locations: "classpath*:mapper/*.xml"
#  configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl